server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phuongtv275/JB-IOC-PTHB260316_Module4_Session07-config.git
          default-label: main
          clone-on-start: true
          force-pull: true
